steps:
  - id: "Executando docker build"
    name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/docker-compose'
    - '.'
images:
- 'gcr.io/$PROJECT_ID/docker-compose'